export const BIBLE_BOOKS = [
  'Genesis',
  'Exodus',
  'Leviticus',
  'Numbers',
  'Deuteronomy',
  'Joshua',
  'Judges',
  'Ruth',
  '1 Samuel',
  '2 Samuel',
  '1 Kings',
  '2 Kings',
  '1 Chronicles',
  '2 Chronicles',
  'Ezra',
  'Nehemiah',
  'Esther',
  'Job',
  'Psalm',
  'Psalms',
  'Proverbs',
  'Ecclesiastes',
  'Song of Solomon',
  'Song of Songs',
  'Isaiah',
  'Jeremiah',
  'Lamentations',
  'Ezekiel',
  'Daniel',
  'Hosea',
  'Joel',
  'Amos',
  'Obadiah',
  'Jonah',
  'Micah',
  'Nahum',
  'Habakkuk',
  'Zephaniah',
  'Haggai',
  'Zechariah',
  'Malachi',
  'Matthew',
  'Mark',
  'Luke',
  'John',
  'Acts',
  'Romans',
  '1 Corinthians',
  '2 Corinthians',
  'Galatians',
  'Ephesians',
  'Philippians',
  'Colossians',
  '1 Thessalonians',
  '2 Thessalonians',
  '1 Timothy',
  '2 Timothy',
  'Titus',
  'Philemon',
  'Hebrews',
  'James',
  '1 Peter',
  '2 Peter',
  '1 John',
  '2 John',
  '3 John',
  'Jude',
  'Revelation'
]

export const BIBLE_BOOK_ALIASES = {
  Genesis: ['Gen', 'Gen.', 'Ge', 'Ge.', 'Gn'],
  Exodus: ['Exod', 'Exod.', 'Ex', 'Ex.', 'Exo', 'Exo.'],
  Leviticus: ['Lev', 'Lev.', 'Lv', 'Lv.'],
  Numbers: ['Num', 'Num.', 'Nm', 'Nm.', 'Nu', 'Nu.'],
  Deuteronomy: ['Deut', 'Deut.', 'Dt', 'Dt.', 'Deu', 'Deu.'],
  Joshua: ['Josh', 'Josh.', 'Jos', 'Jos.'],
  Judges: ['Judg', 'Judg.', 'Jud', 'Jud.', 'Jdg', 'Jdg.', 'Jdgs'],
  Ruth: ['Ru', 'Ru.', 'Rth', 'Rth.'],
  '1 Samuel': ['1 Sam', '1 Sam.', '1Sa', '1Sa.', '1Sam', '1Sam.', 'I Sam', 'I Sam.'],
  '2 Samuel': ['2 Sam', '2 Sam.', '2Sa', '2Sa.', '2Sam', '2Sam.', 'II Sam', 'II Sam.'],
  '1 Kings': ['1 Kgs', '1 Kgs.', '1Ki', '1Ki.', '1Kings', '1Kings.', 'I Kgs', 'I Kgs.'],
  '2 Kings': ['2 Kgs', '2 Kgs.', '2Ki', '2Ki.', '2Kings', '2Kings.', 'II Kgs', 'II Kgs.'],
  '1 Chronicles': ['1 Chr', '1 Chr.', '1Ch', '1Ch.', '1Chron', '1Chron.', 'I Chr', 'I Chr.'],
  '2 Chronicles': ['2 Chr', '2 Chr.', '2Ch', '2Ch.', '2Chron', '2Chron.', 'II Chr', 'II Chr.'],
  Ezra: ['Ezr', 'Ezr.', 'Ez.'],
  Nehemiah: ['Neh', 'Neh.', 'Ne', 'Ne.'],
  Esther: ['Esth', 'Esth.', 'Est', 'Est.'],
  Job: ['Jb', 'Jb.'],
  Psalm: ['Ps', 'Ps.', 'Psa', 'Psa.', 'Psm', 'Psm.', 'Pss', 'Pss.'],
  Psalms: ['Ps', 'Ps.', 'Psa', 'Psa.', 'Psm', 'Psm.', 'Pss', 'Pss.'],
  Proverbs: ['Prov', 'Prov.', 'Pr', 'Pr.', 'Prv', 'Prv.'],
  Ecclesiastes: ['Eccl', 'Eccl.', 'Ecc', 'Ecc.', 'Qoheleth', 'Qoheleth.'],
  'Song of Solomon': ['Song of Sol', 'Song of Sol.', 'Song', 'Song.', 'SoS', 'Cant', 'Cant.', 'Canticles', 'Canticles.'],
  'Song of Songs': ['Song of Sol', 'Song of Sol.', 'Song', 'Song.', 'SoS', 'Cant', 'Cant.', 'Canticles', 'Canticles.'],
  Isaiah: ['Isa', 'Isa.'],
  Jeremiah: ['Jer', 'Jer.'],
  Lamentations: ['Lam', 'Lam.'],
  Ezekiel: ['Ezek', 'Ezek.', 'Eze', 'Eze.'],
  Daniel: ['Dan', 'Dan.'],
  Hosea: ['Hos', 'Hos.'],
  Joel: ['Joe', 'Joe.'],
  Amos: ['Am', 'Am.'],
  Obadiah: ['Obad', 'Obad.', 'Ob', 'Ob.'],
  Jonah: ['Jon', 'Jon.'],
  Micah: ['Mic', 'Mic.'],
  Nahum: ['Nah', 'Nah.'],
  Habakkuk: ['Hab', 'Hab.'],
  Zephaniah: ['Zeph', 'Zeph.', 'Zep', 'Zep.'],
  Haggai: ['Hag', 'Hag.'],
  Zechariah: ['Zech', 'Zech.', 'Zec', 'Zec.'],
  Malachi: ['Mal', 'Mal.'],
  Matthew: ['Matt', 'Matt.', 'Mt', 'Mt.'],
  Mark: ['Mk', 'Mk.'],
  Luke: ['Lk', 'Lk.'],
  John: ['Jn', 'Jn.', 'Jhn', 'Jhn.'],
  Acts: ['Act', 'Act.'],
  Romans: ['Rom', 'Rom.', 'Ro', 'Ro.'],
  '1 Corinthians': ['1 Cor', '1 Cor.', '1 Co', '1 Co.', '1Cor', '1Cor.', 'I Cor', 'I Cor.'],
  '2 Corinthians': ['2 Cor', '2 Cor.', '2 Co', '2 Co.', '2Cor', '2Cor.', 'II Cor', 'II Cor.'],
  Galatians: ['Gal', 'Gal.'],
  Ephesians: ['Eph', 'Eph.'],
  Philippians: ['Phil', 'Phil.', 'Php', 'Php.'],
  Colossians: ['Col', 'Col.'],
  '1 Thessalonians': ['1 Thess', '1 Thess.', '1 Thes', '1 Thes.', '1 Th', '1 Th.', '1Thess', '1Thess.', 'I Thess', 'I Thess.'],
  '2 Thessalonians': ['2 Thess', '2 Thess.', '2 Thes', '2 Thes.', '2 Th', '2 Th.', '2Thess', '2Thess.', 'II Thess', 'II Thess.'],
  '1 Timothy': ['1 Tim', '1 Tim.', '1 Ti', '1 Ti.', '1Tim', '1Tim.', 'I Tim', 'I Tim.'],
  '2 Timothy': ['2 Tim', '2 Tim.', '2 Ti', '2 Ti.', '2Tim', '2Tim.', 'II Tim', 'II Tim.'],
  Titus: ['Tit', 'Tit.'],
  Philemon: ['Philem', 'Philem.', 'Phm', 'Phm.'],
  Hebrews: ['Heb', 'Heb.'],
  James: ['Jas', 'Jas.'],
  '1 Peter': ['1 Pet', '1 Pet.', '1 Pe', '1 Pe.', '1 Pt', '1 Pt.', '1Peter', '1Peter.', 'I Pet', 'I Pet.'],
  '2 Peter': ['2 Pet', '2 Pet.', '2 Pe', '2 Pe.', '2 Pt', '2 Pt.', '2Peter', '2Peter.', 'II Pet', 'II Pet.'],
  '1 John': ['1 John', '1 Jn', '1 Jn.', '1Jn', '1Jn.', 'I John', 'I John.', '1 Jo', '1 Jo.'],
  '2 John': ['2 John', '2 Jn', '2 Jn.', '2Jn', '2Jn.', 'II John', 'II John.', '2 Jo', '2 Jo.'],
  '3 John': ['3 John', '3 Jn', '3 Jn.', '3Jn', '3Jn.', 'III John', 'III John.', '3 Jo', '3 Jo.'],
  Jude: ['Jud', 'Jud.'],
  Revelation: ['Rev', 'Rev.', 'Re', 'Re.', 'Apoc', 'Apoc.', 'Revelations']
}
